apiVersion: v1
kind: Service
metadata:
  name: msdemo-adservice-service
  labels:
    app: msdemo-adservice
spec:
  selector:
    app: msdemo-adservice
  ports:
    - protocol: TCP
      name: grpc
      port: 7000
  type: ClusterIP