apiVersion: v1
kind: Service
metadata:
  name: msdemo-currencyservice-service
  labels:
    app: msdemo-currencyservice
spec:
  selector:
    app: msdemo-currencyservice
  ports:
    - protocol: TCP
      name: grpc
      port: 7000
  type: ClusterIP